/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'lowStockThreshold' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'salePrice' : IDL.Nat,
  'costPrice' : IDL.Nat,
});
export const Time = IDL.Int;
export const SaleRecord = IDL.Record({
  'id' : IDL.Text,
  'productId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'profit' : IDL.Nat,
  'salePrice' : IDL.Nat,
  'costPrice' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'defaultLowStockThreshold' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockAlerts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getSalesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(SaleRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSale' : IDL.Func([SaleRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'lowStockThreshold' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'salePrice' : IDL.Nat,
    'costPrice' : IDL.Nat,
  });
  const Time = IDL.Int;
  const SaleRecord = IDL.Record({
    'id' : IDL.Text,
    'productId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'profit' : IDL.Nat,
    'salePrice' : IDL.Nat,
    'costPrice' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'defaultLowStockThreshold' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockAlerts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getSalesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(SaleRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSale' : IDL.Func([SaleRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };